<?xml version="1.0" encoding="UTF-8"?><testrun name="MainTest" project="java_test" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="java_test.MainTest" time="0.014" displayname="MainTest" uniqueid="[engine:junit-jupiter]/[class:java_test.MainTest]">
    <testcase name="test" classname="java_test.MainTest" time="0.007" displayname="test()" uniqueid="[engine:junit-jupiter]/[class:java_test.MainTest]/[method:test()]"/>
    <testcase name="test2" classname="java_test.MainTest" time="0.006" displayname="test2()" uniqueid="[engine:junit-jupiter]/[class:java_test.MainTest]/[method:test2()]">
      <failure>
        <expected>2</expected>
        <actual>1</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;2&gt; but was: &lt;1&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)&#13;
	at java_test.MainTest.test2(MainTest.java:54)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
